version: '3'
services:
  api:
    build: ./rest-api
    restart: always
    env_file:
      - ./rest-api/.env
    ports:
      - 8080:8080
      - 9229:9229 # Debugger
    command: yarn start:docker
    depends_on:
      - db
    networks:
      - notifications

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    env_file: ./rest-api/.env
    networks:
      - notifications
    volumes:
      - db:/db

#  worker:
#    build: ./worker
#    command: yarn start:docker
#    ports:
#      - 8000:8000
#    depends_on:
#      - redis
#    env_file:
#      - ./worker/.env
#    restart: always
#    volumes:
#      - worker:/worker

#  redis:
#    env_file:
#      - .env
#    image: redis:5.0.4-stretch
#    restart: always
#    volumes:
#      - redis:/data

networks:
  notifications:
    driver: bridge

volumes:
  client:
    driver: local
  db:
    driver: local
  redis:
    driver: local
